spring:
  application:
    name: poolbox
  profiles:
    active: default
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      base-path: /application
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: always
server:
  port: 8080